### ISSUE TITLE
API consumer activation code duplicates pw

### ISSUE THREAD

**Issue by jaredsieling** [pilrhealth/pilrhealth-issues#101]
If you create an API consumer through the developer tools at /apiConsumer/create page, the activation code that gets created should be the name concatenated with the code, as is being done when they add a device for a participant.  However, it currently adds the code twice at the end of the concatenation.

Update this to match how it is created for participant devices.

**Comment by erikriverson** [comment]
@jaredsieling just looked and this looks fixed in develop, so closing
