### ISSUE TITLE
nitrogen participant value edit issue

### ISSUE THREAD

**Issue by MeiResearchLtd** [pilrhealth/pilrhealth-issues#106]
Using the nitrogen.pilr.json definition, which specifies clazz as: com.pilrhealth.settings.DoubleSetting. 

When trying to edit the value for a participant, I cannot get decimal values in the edit box. I can type, for example, "1.", but not a digit after the dot. Inputting a leading dot (i.e., without a leading digit) will remove it immediately. 

I believe we should be able to input values like 1.1 into this field when the clazz is set this way, but perhaps am mistaken. 

![pilr test](https://cloud.githubusercontent.com/assets/4367956/5002240/59bd92ee-69b3-11e4-8cbe-db3187673d07.png)

**Comment by jamespshields** [comment]
Fixed 11/26 by https://github.com/MeiResearchLtd/s4r-general/commit/51fb648b06a2c37720e53a06ff8977694faa6fdc

**Comment by erikriverson** [comment]
looks good , thanks.
