### ISSUE TITLE
consider adding processing job return property 'info'

### ISSUE THREAD

**Issue by erikriverson** [pilrhealth/pilrhealth-issues#112]
We may consider adding a processing job property called 'info' that would contain arbitrary key/value pairs. I don't think there'd be any need to view the data through the app, but it would be stored in the database with other information about the job. This could be used to store things like the Git commit hash for the versions of R, pilr.dpu.r, pilr.utils.r, and whatever package the processing job calls. This would be a step towards being able to reproduce stored calculations in the future as the packages referenced previously are updated.

**Comment by plbrownupnorth** [comment]
This has been addressed.
