### ISSUE TITLE
Second event times changing on selected event resize

### ISSUE THREAD

**Issue by jaredsieling** [pilrhealth/pilrhealth-issues#144]
For 'evtagger' tool.

To reproduce, go into the Event Tag Editor tool, for a participant.  
1. Check the box next to two events so they both show on the plot.  We'll call whichever one you checked first, event #1.
2. Select event #1 to edit by clicking on it, resize one edge, and then hit cancel on the form.  
3. Repeat that process with event #2.  You'll see that event #1 is being editted.

NOTE 1:
It seems the issue is related to the order the events are checked in the table above, because if you first edit event #2, and then #1, the issue doesn't occur.  Also, if you check 3 events, edit #2 and then #1 it doesn't occur, but if you edit #2 and then #3 it does.

**Comment by gelicia** [comment]
Should be fixed in commit 1e8500a. I'm noticing the same type of issues with the handles appearing/disappearing, so I am going to comb through and make sure that is fixed up as well.
