### ISSUE TITLE
API GET data returning for multiple participants

### ISSUE THREAD

**Issue by jaredsieling** [pilrhealth/pilrhealth-issues#153]
When fetching data through the dataset API for a specific participant, it seems to be returning data for all participants.  

TODO: Jared will add more detail  on this.

**Comment by erikriverson** [comment]
Is the query string using the correct key? (I can't remember if it's pt or participant?)

**Comment by jaredsieling** [comment]
Issue was that the method in the DataService used 'participant' in params, but we were setting 'participantCode'.
