### ISSUE TITLE
OpenCPU temp directory name

### ISSUE THREAD

**Issue by jamespshields** [pilrhealth/pilrhealth-issues#154]
On my local OpenCPU VM, I see entries like the following in /var/log/apache2/error.log:

```[Thu Jan 15 15:33:04.315322 2015] [:error] [pid 25613] [client 172.31.48.1:51679] rApache Notice!
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/tmp/ocpu-temp/file640d69b22838': No such file or directory
Traceback:
No traceback available ```

This VM has a directory named /tmp/ocpu-www-data, but no /tmp/ocpu-temp.
I can work around this by creating a symbolic link, but it'd be nice to either fix the underlying issue, or update the ansible script to configure this automatically.

**Comment by erikriverson** [comment]
Thanks for the report, I just saw this for the first time this morning on QA, so going to see when first signs of this error are in the logs. (The directory does exist on QA though, oddly?)

**Comment by erikriverson** [comment]
This was fixed in latest opencpu (https://github.com/jeroenooms/opencpu/issues/128). May have to update your VM opencpu package. Provisioning a new VM would pull the latest Opencpu, where it should be an issue.
