### ISSUE TITLE
Timeout Error When Uploading Large Files

### ISSUE THREAD

**Issue by tdschenk** [pilrhealth/pilrhealth-issues#156]
(I am working on the qa server)

GENEActiv exports data as a binary file which would need to be uploaded to the server in order to undergo processing. The file I have been working with locally contains 7 days of data and is 734MB. When attempting to upload on qa, after 60 seconds my request times out and Chrome brings me to an error page saying:

*The connection to qa.pilrhealth.com was interrupted.*
*Error code: ERR_CONNECTION_RESET*

Perhaps this is as simple as increasing the request timeout limit? Dealing with large files and large jobs (processing these large binary file also takes a long time) may be an issue for the future, I am not familiar with the backend of the system so I don't know.

**Comment by erikriverson** [comment]
@jamespshields This type of file will just be stored in GridFS, NOT parsed and validated against a Concordia schema.

**Comment by jamespshields** [comment]
Excellent, thanks for clarifying!
