### ISSUE TITLE
New project wizard 500 error

### ISSUE THREAD

**Issue by jaredsieling** [pilrhealth/pilrhealth-issues#161]
On step 3 of the new project wizard I received a 500 error.  I had added the 'LIITA3H App' instrument and clicked 'Next' on step 3.  I had previously cleaned the database and had a fresh 'vagrant up' from the provision repo.

![wizard-error](https://cloud.githubusercontent.com/assets/1580148/5862342/b1ca7784-a236-11e4-8e40-ef183dd8baab.png)

**Comment by jamespshields** [comment]
By chance did you leave for a few minutes before coming back and pressing "Next"? I saw this once, but couldn't reproduce it.

**Comment by jaredsieling** [comment]
As followup, I was getting the 'null+null' error after this, so I pulled the fix for that and tried this again.  I still hit this error on my local, but the 'null+null' issue was resolved successfully.

**Comment by jaredsieling** [comment]
The issue seems to have been caused by switching branches WITHOUT restarting the running grails process.  Stopping and starting the grails app fixed the error.
