### ISSUE TITLE
Settings with value of 0 disappear in certain situations

### ISSUE THREAD

**Issue by erikriverson** [pilrhealth/pilrhealth-issues#167]
Instrument settings can have min/max values, for example:

        {
            "clazz": "com.pilrhealth.settings.DoubleSetting",
            "code": "pilrhealth:calrq:in_co2",
            "name": "CO2 In Constant",
            "description": "CO2 In Constant",
            "value" : 0,
            "min" : 0,
            "max" : 1000,
            "required": false
        }

When I actually set the value of this setting to the min (0 in this case), the setting disappears. I don't know if this is something to do with the value of 0 in general, or an edge case that effects min/max values in general. 

Some screenshots may help clarify: 

I have set the value of the CO2 In Constant to the min (0), and saved the setting without any errors. However, when I run the processing job that uses this setting, it claims I have not set it. 

![pilr propane burn 1](https://cloud.githubusercontent.com/assets/122208/5989580/9ab5b1a0-a941-11e4-93d1-170f7a2bd81a.png)

I look at the value by clicking on it (that is, clicking on '0.0') and see it is empty. 

![pilr propane burn 2](https://cloud.githubusercontent.com/assets/122208/5989581/9dda85fe-a941-11e4-8e0c-73dbeba99099.png)

**Comment by jamespshields** [comment]
Hi @erikriverson, I've committed a fix for the presentation issue on the coordinator interface (screenshot 2 above). Could you remind me where to find the job definition that uses this setting?
