### ISSUE TITLE
Feature to fetch any type of 'definition' file from Github

### ISSUE THREAD

**Issue by jaredsieling** [pilrhealth/pilrhealth-issues#169]
Currently, we have the capability to add a new Job Definition to a project by specifying a Github URL, and pilrhealth goes out and fetches the file and adds the definition to the project.  

We think this capability simplifies things greatly, and it would be nice to add it for each place a user could add a definition to a project.  Right now, some of the 'add definition' components are available to users with 'configuration permissions', and others can only be done by platform developers.  Initially, we could focus on allowing a 'configurator' to add:

  Participant variables
  File types
  Datasets
  Dashboard panels
  Jobs

Eventually, we could expand to:

  Instruments
  Project designs

Further, we could potentially have the 'Marketplace' items be a pointer to a specific Github URL, and then we could manage those components centrally, as opposed to having to manage them for each pilrhealth instance/environment.

NOTE: This is a suggestion that came up while brainstorming how to allow 3rd party organizations to contribute and share components they have created, with others.  It isn't an instruction that we should for sure do, but rather something to consider and discuss as a team.

**Comment by jamespshields** [comment]
Superseded by Assembla issue 948.
