### ISSUE TITLE
include localTimestamp in metadata

### ISSUE THREAD

**Issue by erikriverson** [pilrhealth/pilrhealth-issues#171]
When reading data via the API each piece of data returned contains metadata properties 'id', 'timestamp', and 'pt'. For helping with issues regarding time zones, we discussed including the localTimestamp field as an additional metadata property. This would show up when data is read via the API, and in the data set viewer results as column metadata:localTimestamp.

**Comment by jaredsieling** [comment]
@jamespshields This is a high priority issue, if you can get to it next.  We may want to review how we should display this in the data/show page, to somehow indicate UTC versus local clearly.

**Comment by jaredsieling** [comment]
I propose we update to show the localTimestamp value in the "metadata:timestamp" field, and add another field "metadata:timestamp_utc", where we show the utc time.
