### ISSUE TITLE
Still gray text on light gray

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#173]
Mentioned before it's very hard to make out the text that just slightly grayer than the background. How long until we can make all text clear? The full blue and green I can see. But all the gray needs to go away.

**Comment by ijafir** [comment]
@jaredsieling could you point out an exact location where this is happening.  I think an area where this is happening is under the participant show screen in the tabs.  However, the reason why its happening there is b/c those tabs are not active.  If we can get some accurate location of where this is applicable, it will help to update the correct css.

**Comment by jaredsieling** [comment]
@ijafir I think this was filed by Jon (or at least wasn't me), and I'm not sure exactly what he is referring to.  I'm not sure if he is referring to the buttons that are gray, or text somewhere.  We'll have to check with him to get an example.
