### ISSUE TITLE
[Enhancement] Add input_file_types functionality for R processing tools/job definitions

### ISSUE THREAD

**Issue by tdschenk** [pilrhealth/pilrhealth-issues#174]
I am working to create a job with the R Processing Tool that would take in a file uploaded to PiLR as the input, instead of a dataset, as jobs thus far have used. I see there are fields for input_file_types and output_file_types in the job definition ( https://github.com/MeiResearchLtd/s4r-general/wiki/devspec_tool-r-processing ). However, it seems that input_file_types has not been implemented into the system yet. output_file_types works as intended, so I think this is the only field left to be implemented. 

Let me know if I am mistaken about this or if you have further questions/comments.

**Comment by jamespshields** [comment]
That is correct, this feature was deprioritized. Could you request reprioritization on the Assembla issue, briefly describing the use case?
https://www.assembla.com/spaces/pilr-projects/tickets/491-r-processing-tool--create-service-logic-to-handle-job-input-files#/activity/ticket:
