### ISSUE TITLE
User feedback of uploaded files

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#176]
The "processing" state of uploaded files does not seem to refresh automatically, I had to click "reload page" to discover that my file had been properly processed and data added to the target dataset

**Comment by jaredsieling** [comment]
We don't have a clean way to deal with this, so in the short term perhaps we should put a popover on the 'processing' icon in the table, so when they hover over it, it tells them they must refresh to page to see if the status has changed?
