### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by jamespshields** [pilrhealth/pilrhealth-issues#186]
On the Liitah/AppPlus server, invalid data is being erroneously validated. For example submitting data without metadata doesn't cause validation failure as it should. Possibly related to this commit?:
https://github.com/MeiResearchLtd/s4r-general/commit/7661109b7911d4e513e43cc585ea1f509c46c308

**Comment by ijafir** [comment]
Hi James, to speed up this resolution of this task, can you please specify - 
1.)The dataset
2.)A copy of the sample data being inserted
3.)The branch the error is occuring on so I can debug locally
4.)The insertion method ie apiPost with the url

**Comment by jamespshields** [comment]
Yeah I will track down some more details...

**Comment by jamespshields** [comment]
Nevermind, can't seem to reproduce this now.
