### ISSUE TITLE
Apostrophes are showing as three question marks on CSV import

### ISSUE THREAD

**Issue by jaredsieling** [pilrhealth/pilrhealth-issues#212]
When importing a CSV file of content for Food Suggestions or Information cards, if the text has an apostrophe in it, it is showing on the website and app as three questionmark icons.

**Comment by jamespshields** [comment]
Moved to assembla: https://www.assembla.com/spaces/pilr-projects/tickets/1013-apostrophes-are-showing-as-three-question-marks-on-csv-import
