### ISSUE TITLE
Little box with arrows should be labeled

### ISSUE THREAD

**Issue by mschultz6** [pilrhealth/pilrhealth-issues#224]
![screenshot from 2015-06-08 10 59 00](https://cloud.githubusercontent.com/assets/12631988/8039151/6f921af4-0dcd-11e5-8971-663c52109e88.png)

In 'Datasets with Data' row:
On the far right you'll see a little blue box with a swoopy arrow coming out of it.
No info icon, and the column is not labeled, so possibly labeling the column or the box would ease navigation.

**Comment by jaredsieling** [comment]
All the icons in table rows should show a label on hover.  If this is too slow, we could add a popover to emphasize what it will do?
