### ISSUE TITLE
Importing Tools/Instruments

### ISSUE THREAD

**Issue by mschultz6** [pilrhealth/pilrhealth-issues#227]
In Project Design/Configuration where Tools and Instruments can be imported, clicking on the individual import in each 'section' gives the same Import box as just clicking the big 'Import Project Components or Configuration' at the top of the page. In addition, they all do the same thing. 

For example if I click on the Tools section 'Import', then I could import an Instrument even though it's in the tool section. (The instrument, when imported, still goes under the instrument section which is correct, but seems counter intuitive to be able to import an instrument etc through the Tool section).

Even if the functionality doesn't change for this (doesn't necessarily need to), I would recommend that when a section's 'import' is clicked, that there's a different Label for each section. 

Overall, this 'bug' isn't really a bad thing functionally, but it detracts from the intuitive-ness of the interface.

**Comment by jaredsieling** [comment]
@mschultz6 The modal that shows is the same one, when all buttons are clicked, so it wouldn't be possible (without restructuring the whole modal) to change just the modal title.  

Another option would be to remove the buttons further down the page and just instruct them to click the button at the top to add one? Or update the text of the buttons to always match?

Thoughts?

**Comment by mschultz6** [comment]
@jaredsieling Seems like it'd probably be easier to just have one button.
