### ISSUE TITLE
Explain card

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#236]
We need a lot more description of cards that can be added. For example, what's the difference between "Deliver a survey" and "Delivery queue of triggered surveys"? Why are Question types (single/multiple choice) presented at the same level as an entire survey?

**Comment by jaredsieling** [comment]
One way to do this right on the card type popup would be to add an 'info' icon on the right side of each item as a popover, and if hovered over it shows a description of that card type.
