### ISSUE TITLE
Selecting Default Template in EMA_Brach_Testing Project on Project Design menu causes 500 error

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#260]
selecting the Default Template option in this view on qa.pilrhealth.com results in a 500 error

![image](https://cloud.githubusercontent.com/assets/11665857/9552569/c2376e62-4d7e-11e5-9fc0-2fef8bc5fa0e.png)

I can create the same error by selecting the Default Template option from the Template sub-option under the Instruments Menu on the Project Components menu

![image](https://cloud.githubusercontent.com/assets/11665857/9552680/9317d670-4d7f-11e5-9cb7-5cfb703d7099.png)

**Comment by tdschenk** [comment]
@bikerjohn
I am trying to recreate this error but am unable to. Do you happen to know what recent steps occurred to get the project design in this state (specifically adding/deleting templates and periods)?

**Comment by bikerjohn** [comment]
FYI,
I created a new project, and used the EMA config from EMA_Branch_Test.  I
used the Default Template too.  I can't recreate the 500 error.

Regards,

On Tue, Sep 8, 2015 at 11:32 AM, Tyler Schenk <notifications@github.com>
wrote:

> @bikerjohn <https://github.com/bikerjohn>
> I am trying to recreate this error but am unable to. Do you happen to know
> what recent steps occurred to get the project design in this state
> (specifically adding/deleting templates and periods)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pilrhealth/pilrhealth-issues/issues/260#issuecomment-138622989>
> .
>



-- 
John J. Shade

**Comment by bikerjohn** [comment]
I discussed it with Jared.  If he can't come up with a reason why this
might have happened, I would suggest that we close the ticket with an
explanation that we could not recreate the problem on a new project.

Regards,

On Tue, Sep 8, 2015 at 1:48 PM, John Shade <jshade@meinergy.com> wrote:

> FYI,
> I created a new project, and used the EMA config from EMA_Branch_Test.  I
> used the Default Template too.  I can't recreate the 500 error.
>
> Regards,
>
> On Tue, Sep 8, 2015 at 11:32 AM, Tyler Schenk <notifications@github.com>
> wrote:
>
>> @bikerjohn <https://github.com/bikerjohn>
>> I am trying to recreate this error but am unable to. Do you happen to
>> know what recent steps occurred to get the project design in this state
>> (specifically adding/deleting templates and periods)?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pilrhealth/pilrhealth-issues/issues/260#issuecomment-138622989>
>> .
>>
>
>
>
> --
> John J. Shade
>



-- 
John J. Shade

**Comment by jaredsieling** [comment]
I cannot see anything in recent commits that would have effected this.  I'll close the issue and we can reopen if anyones sees it again.
