### ISSUE TITLE
Dashboards don't display current day if no data has been submitted (all participants have no new data)

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#261]
On the qa platform, I ran the dashboards first thing this morning.  I had not generated any new test data over the weekend.  The last date displayed was 8/27/2015 (even though today's date is 8/31/2015).  I expected to see 3 days of all 0(zero) values.  I could not get the 29th, 30th, and 31st to display even if I selected a custom period.

The dashboard display showed the 29th - 31st when I created some test data records.

**Comment by tdschenk** [comment]
@bikerjohn Currently there isn't a way for my R function to know what dates are passed into the filter - it just sees what timestamp the last data point has and assumes that is the end. It should be possible to update the wrapper function (https://github.com/MeiResearchLtd/pilr.dash.r/blob/master/R/pilrdash-package.r) to pass those filters in. I will look into it today.
