### ISSUE TITLE
Deleting a project not working on qa

### ISSUE THREAD

**Issue by tdschenk** [pilrhealth/pilrhealth-issues#262]
Deleting a project through the project design page goes through all of the expected windows, ending with "Project Deleted", but the project does not actually get deleted.

Deleting a project through an organization is not working, either. After clicking on the trash icon, the screen just dims but no popup appears.

**Comment by jaredsieling** [comment]
Note that trying this on my local environment, creating a new project and then deleting it, seems to be working.  Not sure what would be the difference.

**Comment by jaredsieling** [comment]
No errors or warning are showing in the log for these actions.

**Comment by tdschenk** [comment]
@jaredsieling 
I just tested creating a brand new project on qa and deleting it. It works through the Project Design page but NOT through an organization (still just a dimmed screen for me). When I attempt to delete through an organization on my local I also get this behavior.

So, it appears to be an issue with projects that existed before these changes were deployed.

**Comment by tdschenk** [comment]
@jaredsieling 
The reason it is not working through an organization is that the trash can icon tries to link to a delete function Matt had made in the organization controller, but it looks like you deleted that and were just trying to use the one in the project controller. It might be a good idea to leave the two functions in both controllers since one should redirect to the main "home page" and the other to the organization page.

**Comment by MeiResearchLtd** [comment]
BUG: make ticket
