### ISSUE TITLE
Compressed View Report is Not Returning Data for Multiple-Choice, Multi-Select Question

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#266]
This report creates a flattened record that is useful for analysis as all of the survey responses for a single user's response to a survey are output in a single row.  At the moment, the report engine does not appear to handle the output for a multiple choice multi select question correctly.  No data is returned.  The challenge for this type of questions, is that multiple values are returned for a single question.  If we stick to the current layout, this should result in multiple columns for this one question.

**Comment by jaredsieling** [comment]
@bikerjohn I have fixed this, but have a couple questions:

1. For multiple select columns, if that question was responded to, the value in the cell for each column is 'true' or 'false', indicating if that option was checked.  Do you want this, or should it be '1' or '0'?
2. For Yes/No questions, I believe that I'm seeing the values in the cells for responses being 'Yes' or 'No'.  Do you want that, or should it be '1' or '0'?

**Comment by bikerjohn** [comment]
Either could work.  I am guessing that it might be easier for producing
counts if we returned a number ("1" or "0").  This would allow researchers
to sum values in a column to see what the selection frequency is.  They
could also do this for the "true" "false" values with a little more work.

Under separate feature I am asking for a survey report which would output a
table that consists of question title, text, value, and answer text.  They
could then use this to merge this data back to format human friendly output.

Regards,

On Tue, Sep 15, 2015 at 10:35 AM, Jared Sieling <notifications@github.com>
wrote:

> @bikerjohn <https://github.com/bikerjohn> I have fixed this, but have a
> couple questions:
>
>    1. For multiple select columns, if that question was responded to, the
>    value in the cell for each column is 'true' or 'false', indicating if that
>    option was checked. Do you want this, or should it be '1' or '0'?
>    2. For Yes/No questions, I believe that I'm seeing the values in the
>    cells for responses being 'Yes' or 'No'. Do you want that, or should it be
>    '1' or '0'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pilrhealth/pilrhealth-issues/issues/266#issuecomment-140434360>
> .
>



-- 
John J. Shade
