### ISSUE TITLE
BUG: submitting an issue from qa.pilrhealth resulted in multiple github isssues

### ISSUE THREAD

**Issue by mgm7734** [pilrhealth/pilrhealth-issues#286]
I got more than 10 copies of the 'project search broekn' issue.  Closed duplicates

**Comment by tdschenk** [comment]
@mgm7734 I just fixed an issue where the feedback form was not displaying a confirmation screen. So when you clicked submit, it would submit to github but there was no change/visual confirmation on the qa screen. When you tried to submit this issue, could you just have clicked Submit many times without realizing it was actually submitting?
