### ISSUE TITLE
tried to submit feedback

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#341]
hit save-nothing happened on my screen but Tyler confirmed that feeback was actually submitted

**Comment by tdschenk** [comment]
This was being caused by the submission date not being parsed correctly. I have fixed the bug on qa and confirmed it is working.

https://github.com/MeiResearchLtd/s4r-general/commit/687c121dbff7c366616903c009d5ee03b5542153
