### ISSUE TITLE
Invalid characters in participant <something>

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#378]
Got this message when trying to create a participant (can't recall the field label, this message box covers it up). It probably means a whole bunch of characters aren't allowed. We need to tell people what they can do before they get an error. Or, at least make the msg easier to understand (don't tell what they can't do). Property [code] of class [class com.pilrhealth.ParticipantCommand] with value [Jon at OW] does not match the required pattern [[A-Za-z0-9_:-]+]

**Comment by mgm7734** [comment]
GORM let's you optionally specify a message int the constraint def.
We need to use this where ever regex is used.  English please!
