### ISSUE TITLE
Participant Detail Screen Not Showing Instrument

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#397]
I created a project called DualCohort on beta with two groups (control and treatment), with 2 templates (control and treatment).  I assigned the same emaconfig for both templates.  I then added participants.  The participant I added to the control group behaved the way I expected, but the participant I added to the treatment group did not.  I will attach a screen shot from the participant detail screen.  There is no instrument displayed, even though I have assigned a start date for their active period.

**Comment by bikerjohn** [comment]
![pilr_import_bundle_org_err_msg](https://cloud.githubusercontent.com/assets/11665857/11542684/1dc78af8-98fe-11e5-8303-2703940f8107.JPG)

here is the link to the screen shot

**Comment by bikerjohn** [comment]
![pilr_instrument_bug](https://cloud.githubusercontent.com/assets/11665857/11542762/83dcfa26-98fe-11e5-8f42-4d11950d0a09.JPG)

Here is the screen shot

**Comment by tdschenk** [comment]
Ignore the above reference, the commit is linked to wrong issue.
