### ISSUE TITLE
Data is Not Showing Correctly on the Data Overview Screen

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#398]
This screen appears to be pulling data differently than the reports created by the Browse Data option.  I will attach screen shots to show how the reports differ.

**Comment by bikerjohn** [comment]
![pilr_databrowse_report_byuser](https://cloud.githubusercontent.com/assets/11665857/11546689/6acdeeb2-9914-11e5-943a-dc6e1cdd797a.PNG)
![pilr_dataoverview_bug(https://cloud.githubusercontent.com/assets/11665857/11546690/6acebad6-9914-11e5-95da-efb80e225de8.PNG)

The first file has the unexpected result.  It shows the participant as having completed a survey when 
in fact they have not.

**Comment by bikerjohn** [comment]
![pilr_databrowse_report_byuser](https://cloud.githubusercontent.com/assets/11665857/11546744/b334e278-9914-11e5-9d6b-17bd8d698ae8.PNG)
![pilr_dataoverview_bug](https://cloud.githubusercontent.com/assets/11665857/11546745/b339ca04-9914-11e5-9904-f949f30c019d.PNG)

the first file shows the bug -- that view makes it look like the participant has completed a survey when in fact they have not.

**Comment by tdschenk** [comment]
@bikerjohn Are you saying it looks like he has completed a survey because there are data points in the App Log dataset? There are two datasets for EMA: App Log and Survey Data. Completed surveys show in Survey Data which is empty here. App Log contains other information (like log-ins and opening the app).

**Comment by bikerjohn** [comment]
No. Jon used the app, but did not complete a survey. The one page appears
to be inaccurate.

**Comment by tdschenk** [comment]
I see the error now, my mistake.
