### ISSUE TITLE
Dashboard not Displaying -- throws attached error -- happens on qa and beta

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#405]
I am now getting the following error message when I go to the Coordinate Page on projects where I have dashboards showing.

![image](https://cloud.githubusercontent.com/assets/11665857/11720571/611bedee-9f25-11e5-9900-9c45b85600cd.png)

This is happening on both qa and beta.  It was not happening when I did all of the automated testing at end of last week.  Not sure what happened.  First time I saw the error was yesterday.

**Comment by tdschenk** [comment]
@bikerjohn Are you still experiencing this issue? I just tested a dashboard on qa and it loaded correctly for me.

**Comment by bikerjohn** [comment]
I am not having that problem anymore.  Not sure why it occurred.  I got the
error right after last weeks deployment.  I can't recreate it now, so I
think we should close it.

On Wed, Dec 16, 2015 at 11:44 AM, Tyler Schenk <notifications@github.com>
wrote:

> @bikerjohn <https://github.com/bikerjohn> Are you still experiencing this
> issue? I just tested a dashboard on qa and it loaded correctly for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pilrhealth/pilrhealth-issues/issues/405#issuecomment-165186229>
> .
>



-- 
John J. Shade
