### ISSUE TITLE
Plotting options-Plot Set up, no data field entry

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#407]
Server: qa.pilrhealth.com
Page: /project/nusi_kee_study_phase/quickPlotItem/create/566ef369e4b08f6a8355b828
User: ewohlers
Project: nusi_kee_study_phase

The data field drop down is not available after the datasets and time field are selected. It worked for the first quick plot I set up, but not the second. I tried changing the data set selection. Data field drop down was still unavailable.

**Comment by jmusacchio-gap** [comment]
Couldn't reproduce it

**Comment by tdschenk** [comment]
@jmusacchio-gap This only occurs when the id(?) is passed through with the URL. It's not clear to me when this happens and when it doesn't, though.

For example, if I access the page through URL:
/project/nusi_kee_study_phase/quickPlotItem/create/566ef369e4b08f6a8355b828
I get this bug. I think you can replicate this on any project by just putting any id in the URL.

But sometimes it just uses the URL:
/project/nusi_kee_study_phase/quickPlotItem/create
And in this case the page functions correctly.

**Comment by jmusacchio-gap** [comment]
My inclination is that could be a problem regarding to javascript execution, could be possible that some javascript is trying to wire an event handler when DOM doesn't exists. That could explain the random nature of the problem.

**Comment by jmusacchio-gap** [comment]
probably wrapping the javascript code with $(document).ready(function(){ //code }); will fix it
