### ISSUE TITLE
Added Project Not Showing in Organization Menu

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#413]
On the QA platform I am seeing the following behavior.
If I go to an organization and create a project.  The project gets added to the system (viewable under my projects), but I don't see it as a project in the Organization menu.  First noticed the behavior on Sunday when I started testing some new scripts.
This worked on Thursday when I ran the Selenium IDE regression, as I have a test case that creates and later deletes a project as a user.  This can no longer be done.

**Comment by ijafir** [comment]
During the implementation of feature manager, the organization on step 2 gets set to null.  Please see feature manager implementation

**Comment by bikerjohn** [comment]
So, can I summarize -- this was an unintended side affect of the changes
associated with giving us (MEI) the ability to show or hide features by
configuation.

Regards,

On Mon, Dec 21, 2015 at 2:46 PM, Imad Jafir <notifications@github.com>
wrote:

> During the implementation of feature manager, the organization on step 2
> gets set to null. Please see feature manager implementation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pilrhealth/pilrhealth-issues/issues/413#issuecomment-166413360>
> .
>



-- 
John J. Shade
