### ISSUE TITLE
Data Viewer Column Picker and View Not Working for participant id

### ISSUE THREAD

**Issue by plbrownupnorth** [pilrhealth/pilrhealth-issues#424]
PB working on project B-Mobile Test#2 on beta server. From individual participant page, choose Data and then data set Lifespan Activity Classification for partcipant 101. Then deselect participant id column and hit view. Get all records for all participants! Wanted view of participant 101 data only, but without the participant id column showing.

**Comment by paul-ferguson** [comment]
This has been fixed now.
