### ISSUE TITLE
Data Viewer-Retain Columns when clearing a search

### ISSUE THREAD

**Issue by plbrownupnorth** [pilrhealth/pilrhealth-issues#429]
Erica and I created a view of calorimeter data that included a subset of columns of interest. We then filtered on one of the columns to get a subset of the rows. When we cleared the search column, we got back all columns. Would prefer to maintain the reduced column set, until and unless with reactivate columns.

**Comment by bikerjohn** [comment]
Test Procedure
Login
Select project with data
Select Instrument
Select Survey Responses
Set Date Range and User Group
Run Query
Get Data Viewer for Survey Answer Data
Filter on Survey Submit rows
Hit Reset Button
Columns still filtered as desired
