### ISSUE TITLE
Bulk Update Does not Assign Instrument for New Participant when Schedule is set

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#432]
Tested the bulk update for use in setting the period start dates for a group of new participants.
Created project with multiple periods and multiple groups
Added participants to groups and periods, but did not schedule them (assign start dates)
Used the bulk update function to set the period start / end dates
Schedule was set for the participant, but the process did not assign an instrument to the participant which means they can't use the mobile app.  If we use the participant detail gui, the instrument gets assigned when the schedule is set (presuming that everything is linked correctly in the project -- verified for this project)

**Comment by paul-ferguson** [comment]
Also in QA for some reason you can't change multiple participant instrument settings at the same time. If you do one at a time it works though. This was discovered while working with project Calorimeter Test Project.

**Comment by paul-ferguson** [comment]
You can now edit multiple participant settings at the same time now.

**Comment by bikerjohn** [comment]
I put the test procedure in the Assembla ticket.  I did test this yesterday and it is working.  Used a bulk import which creates new participants with nothing, and then used the bulk edit to successfully assign all the required pieces.
