### ISSUE TITLE
Bulk Load Does Not Look Like it is Importing first Record in File

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#440]
Created a new project
used the bulk load feature to load participants
I am including a couple of screen shots.
This is the source file
![bl_test2_source](https://cloud.githubusercontent.com/assets/11665857/12278621/c722327e-b947-11e5-963e-26bb27ab967d.PNG)

This is what was successfully loaded.  Note that participant 2040 does not get into the success list.
![bl_test2_success_modal](https://cloud.githubusercontent.com/assets/11665857/12278643/e08da130-b947-11e5-84c0-08331948cbc8.PNG)

Finally, you can see that user 2040 is not in the project
![bl_test2_pilrresults](https://cloud.githubusercontent.com/assets/11665857/12278683/fc5a9df0-b947-11e5-8514-89f1794af01b.PNG)

user 2040 is the first record, so it appears that we are not processing the first record

**Comment by jmusacchio-gap** [comment]
Not sure whether this is an issue cause the bulk add participant page says at the bottom, that the csv file should have a header as row, I tried to be consistent with the approach that was already in place for uploading Info cards.
If you think that we should remove the header row let me know.

**Comment by bikerjohn** [comment]
Juan and I went through this.  The first row is treated like a header row.  The documentation on the Bulk Import screen notes this (I missed it when I was testing).  Went back, added the header and the process created the expected results.  I am closing this issue.
