### ISSUE TITLE
Notification expiration by time of day

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#444]
Server: qa.pilrhealth.com
Page: /project/newbuildertest/trigger/index
User: pbrown
Project: newbuildertest

Do not see any way to set no time of day. Defaults to 1am. Is that intentional?

**Comment by jmusacchio-gap** [comment]
Closed the issue based on a conversation with Phyllis, It will be a new feature if we decide to change in the feature.
