### ISSUE TITLE
Enable open participant registration?

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#456]
Server: cloud.pilrhealth.com
Page: /project/jmdemo1/project/admin
User: jmoon
Project: jmdemo1

"Enable open participant registration?" is the only option we have for security settings? I thought we discussed some other things. 

The explanation needs to be re-written. I don't understand what it means or how to use it.

**Comment by paul-ferguson** [comment]
Does this explanation work to more clearly define what this setting does?

By enabling open participant registration end users can enroll as new participants in your project. This is done either from the "I want to register" action on the login page or through a similar method on the instrument itself. A new participant (along with device login credentials) will be generated. Disabling open registration prevents end users from enrolling and creating participants under your project.

**Comment by plbrownupnorth** [comment]
Talking with customer on this. Will write up ticket for backlog.
