### ISSUE TITLE
Cannot delete a project from organisation

### ISSUE THREAD

**Issue by welsh11** [pilrhealth/pilrhealth-issues#459]
1) Created a project
2) Added instrument and configured default period/template
3) Added participant, scheduled and added device
4) Deleted participant
5) Deleted instrument
6) Attempted to delete project from organisation - get a 500 error

**Comment by bikerjohn** [comment]
Test Process
Ran automated Test Suite
Created Project from Bundle
Added / Activated a Participant
Deleted Project
Project Successfully deleted

**Comment by welsh11** [comment]
Thanks all!
