### ISSUE TITLE
Enter event tag start and stop times as 24 hr time

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#470]
Server: qa.pilrhealth.com
Page: /project/calorimeter_test_project/evTagEditor/show
User: ewohlers
Project: calorimeter_test_project

Enter event tag start and stop times as 24 hr time instead of AM and PM

**Comment by jmusacchio-gap** [comment]
Already fixed it and pushed to release branch, waiting for QA deploy to mark it as ready for test

**Comment by ewohlers1** [comment]
Can x-axis on the graph be changed to 24 hours too?
