### ISSUE TITLE
500 error when trying to view tagged events

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#475]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/participant/show/56b3d691e4b006b540013544
User: ewohlers
Project: multiple_n2_test

When I press the blue error for the tagged events dataset, I get a 500 error. It looks like the viewer for the other datasets works.

**Comment by jmusacchio-gap** [comment]
Querying MongoDB on QA found out that the following collection:

 db["pilrhealth:time_analysis:tagged_event:data:55e60a74e4b0b616ea63c785"]

changed metadata timestamp value from ISODate("string date") to "string date", so means that at some point a data update performed that change. Found out that DatasetService.validateAndUpdateCollectionData method performs like a validation of the metadata timestamp instance to set the localTimestamp

def localTimestamp
if (jsonData.metadata.timestamp instanceof java.util.Date){
  localTimestamp = jsonData.metadata.timestamp
}
else {
  localTimestamp = Util.parseLocalDate(jsonData.metadata.timestamp)
}

But then the metadata is updated in DB and if the jsonData.metadata.timestamp is not instance of Date it will be stored as an String date. Can someone validate this so I can perform the corresponding change?

**Comment by jmusacchio-gap** [comment]
BTW the 500 error is due to _dateOutput template executes <g:formatDate formatName="msexcel.datetime" date="${column.getValue(record)}" /> passing in date string instead of a Date object.
Previous comment details why we ended up passing an string instead of a date object.

**Comment by jmusacchio-gap** [comment]
This is a mongo query to print which collection datasets have the above problem

db.getCollectionNames().forEach(function(col){
    var data = db[col].find( { "metadata.timestamp" : { $type : 2 } } )
    if (data.length() > 0) {
        print(col)
    }
})

Result on QA:

pdnihl:mmm:miles_moved:data:55a6c4f5e4b02ccdad900398
pdnihl:mmm:miles_moved:data:55bf93dce4b0e50f00d1a9c5
pilrhealth:mobile:personal_venue:data:55fbf171e4b0bd693c60bf3d
pilrhealth:time_analysis:tagged_event:data:55e60a74e4b0b616ea63c785
pilrhealth:time_analysis:tagged_event:data:560c05c6e4b0063932b191af
pilrhealth:time_analysis:tagged_event:data:56b0d401e4b07cdcb68f404f
