### ISSUE TITLE
Event editor plots in Firefox

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#476]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/evTagEditor/show
User: ewohlers
Project: multiple_n2_test

Event editor plots are not displaying correctly in Firefox

**Comment by ewohlers1** [comment]
![image](https://cloud.githubusercontent.com/assets/6774942/12992333/66e5af36-d0d9-11e5-8b25-2472c32e4df9.png)

**Comment by jmusacchio-gap** [comment]
Refresh the browser cache, just it case, cause was a change in a javascript file

**Comment by ewohlers1** [comment]
I verified in Firefox. It is working. 

Mark will you close this ticket? thanks
