### ISSUE TITLE
Cant use bottom scroll bar unless scroll to end

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#477]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/data/show
User: ewohlers
Project: multiple_n2_test

I would like the the scroll bar to be usable when looking at the headers.

**Comment by jmusacchio-gap** [comment]
Added a top bar to be able to perform horizontal scrolling from top and also added the sticky header feature so the table header follows user vertical scroll.
