### ISSUE TITLE
home_page_text_not_appropriate

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#479]
Test Procedure
Login

![pilr_home_page_bug](https://cloud.githubusercontent.com/assets/11665857/13033891/d07c8906-d2eb-11e5-9dd1-be4f5dee4a13.PNG)
Note the text that begins
"We noticed that you are not a member of a project..." in the upper left text box.  This is incorrect  Is this supposed to show all of the time, or is it supposed to show only when a new member joins the site.  If it is supposed to show all of the time the text needs to be rewritten.
If it is supposed to show only for new members, the logic is not working correctly.

**Comment by jmusacchio-gap** [comment]
Fixed it waiting for a QA deploy.
