### ISSUE TITLE
pilr_dashboards_not_running

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#480]
The dashboards do not complete running.  They are giving an error
![pilr_dashboard_error](https://cloud.githubusercontent.com/assets/11665857/13051163/54017436-d3bd-11e5-849f-890aaab796d6.PNG)

**Comment by pilrhealth** [comment]
A bug was preventing error messages from opencpu from being shown.  So any problems should now be with particular jobs

**Comment by bikerjohn** [comment]
test procedure
login
select project with dashboards
dashboards complete without error
