### ISSUE TITLE
Request from Paso del Norte

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#493]
Server: cloud.pilrhealth.com
Page: /organization/paso_del_norte_institute_for_healthy_living/show
User: pbrown
Project: null

Would really like ability to set max number of participants per project themselves. They will have many many projects and very inconvenient to have to call us every time they need limit raised from the default of 30.

**Comment by pilrhealth** [comment]
Do we want a quota at the org level?   (limit total particiapnts of all project) This makes most sense to me.
Is there a point to a project quota that they can change themselves?
There are other approaches, too.

**Comment by plbrownupnorth** [comment]
Added a ticket to backlog
