### ISSUE TITLE
500 error trying to run the processing job

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#494]
Server: qa.pilrhealth.com
Page: /RProcEditor/history
User: ewohlers
Project: multiple_n2_test

500 error running the Human study job for GF participant. Created Regression and Misc event tags for the participant

**Comment by mario-camacho2** [comment]
seems duplicated from 490

**Comment by mario-camacho2** [comment]
Fix for 490 already available. Please double check in order to determine if this is a different a bug.
