### ISSUE TITLE
500 error when setting condition in EMA Builder

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#497]
Server: qa.pilrhealth.com
Page: /trigger/saveCondition
User: pbrown
Project: actigraph_epoch_test_5

In Actigraph Epoch Test 5 on qa, tried to set time window condition; when hit Save get 500 error; condition not saved

**Comment by jmusacchio-gap** [comment]
Already fixed it seems that a previous commit removed 2 required import sentences from EmaOtsConfigService.groovy class

import com.pilrhealth.instruments.ema_ots.triggers.TriggerActionType
import com.pilrhealth.instruments.ema_ots.triggers.TriggerConditionType

**Comment by plbrownupnorth** [comment]
We have now disallowed conditions to be set on time window Events.
