### ISSUE TITLE
More on faint font

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#501]
Server: cloud.pilrhealth.com
Page: /project/ag_health_test_project/emaOtsConfig/survey
User: jmoon
Project: ag_health_test_project

We still have gray text that is too light, not just the color text being too light. For example, the explanation "Surveys are delivered to participants as a series of 'cards', presented in order...." on this page is nearly impossible to read. So is white on pale gray such as "Save Order Updates".

**Comment by plbrownupnorth** [comment]
Moving this to a backlog ticket--broad topic of improving UI
