### ISSUE TITLE
Suggest adding an upload option

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#503]
Server: cloud.pilrhealth.com
Page: /project/travel_log/emaOtsConfig/editCard
User: daperezalba
Project: travel_log

I was wondering if we could do a straight image upload for this instead of only having access to a URL. This would be convenient for when I want to simply scan an image or document and add it. I don't want to figure out how or where to post the image every time.

**Comment by plbrownupnorth** [comment]
Discussed with customer and explained that he could store all his images in a common location like a Google Drive folder so he does not need to manage tracking where images are on the internet and can build a reusable "library" for his organization. He is OK with feature as is.
