### ISSUE TITLE
Auto-sync for EMA app

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#505]
Server: cloud.pilrhealth.com
Page: /project/travel_log/trigger/index
User: daperezalba
Project: travel_log

We noticed that changes made do not automatically update on EMA. My phone was not synced, therefore I did not get a trigger notification. The other person did sync, therefore receiving the notification. Could an auto-sync be possible?

**Comment by plbrownupnorth** [comment]
Misunderstanding by customer of how auto sync works
