### ISSUE TITLE
Self-report survey card no longer available

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#508]
Server: cloud.pilrhealth.com
Page: /project/juan_test/emaOtsConfig/builder
User: daperezalba
Project: juan_test

For some reason, the self-report card under the App tabs is no longer available. Could someone please look into this.

**Comment by jmusacchio-gap** [comment]
There was no self-report card type under the App tabs. Self-Report is a boolean flag on the Survey.

**Comment by plbrownupnorth** [comment]
This was intentional with update to v2_api
