### ISSUE TITLE
Card bank/import option

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#509]
Server: cloud.pilrhealth.com
Page: /project/vb_team_management/emaOtsConfig/builder
User: daperezalba
Project: vb_team_management

Having an option to interchange/import cards and/or sections from different projects would be very helpful. Perhaps having a card bank available.

**Comment by plbrownupnorth** [comment]
Moved to PiLR Health backlog as a new feature.
