### ISSUE TITLE
Dashboards show in Job History

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#510]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/RProcEditor/history
User: tschenk
Project: multiple_n2_test

On the Job History page, dashboards are also being included in the list of ran jobs. Since these are loaded each time the project's dashboard page is refreshed it is cluttering the list.

When I try to click on one of the dashboard entries it gives me a 500 error. 

I would suggest not showing dashboards at all in this list (this was the behavior in the past, not sure when or why it changed).

**Comment by tdschenk** [comment]
Merged into new issue:

https://github.com/pilrhealth/pilrhealth-issues/issues/515
