### ISSUE TITLE
Dashboards show in two places in Project Config

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#511]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/jobDef/index
User: tschenk
Project: multiple_n2_test

If the R Processing Tool is enabled for a project, dashboards for that project will appear in the list of Jobs as well as the list of Dashboards within the project config page.

Should only appear in the Dashboards section.

**Comment by tdschenk** [comment]
Merged into new issue:

https://github.com/pilrhealth/pilrhealth-issues/issues/515
