### ISSUE TITLE
Save order updates not working properly

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#512]
Server: cloud.pilrhealth.com
Page: /project/vb_team_management/emaOtsConfig/builder
User: jaaguilera2
Project: vb_team_management

I tried to change order and when clicking save it doesn't save the  new order

**Comment by jmusacchio-gap** [comment]
This issue was already fixed on https://www.assembla.com/spaces/cACHIMvRir44okacwqjQYw/tickets/new_cardwall?default_list_cardwall=milestone:9672663#ticket:1552
Probably the fix was not yet deployed to cloud server.
