### ISSUE TITLE
Lack of "Actions" options

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#513]
Server: cloud.pilrhealth.com
Page: /project/vb_team_management/trigger/index
User: daperezalba
Project: vb_team_management

I was under the impression that every Event would give me a list of Actions but the only Action I have noticed is the "Survey Notification". Expanding the Actions would be very helpful especially ones that would offset other triggers or maybe just providing a message instead of survey notification.

**Comment by plbrownupnorth** [comment]
Discussed with customer and explained more about how actions work. He is now OK with feature as is.
