### ISSUE TITLE
Setting Participant Period dates

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#521]
Server: cloud.pilrhealth.com
Page: /project/multipleepochtestema/participant/period/57056089e4b0e362f708e766
User: pbrown
Project: multipleepochtestema

Making me choose both start and end date even though period defined as 14 days with no override. Expected to just pick start date per usual process.

**Comment by tdschenk** [comment]
Once a period is scheduled, two buttons appear - one to "edit the period and epoch dates" and the other to "reschedule the period". The first allows you to select both start and end dates, while the second only allows you to select a start date.

I think that the current functionality is working as intended, allowing selection of both start and end dates on this screen. If we don't want this, I think it would make more sense to just remove the first button and only have the option to reschedule the period by start date. Do you have an opinion on this?

**Comment by tdschenk** [comment]
Leaving functionality as is here. Will update tooltips slightly to be more intuitive.
