### ISSUE TITLE
500 error when adding CalRQ instrument to template

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#524]
Server: qa.pilrhealth.com
Page: /project/calorimeterprojectdemo/template/saveInstrument/570fbb08e4b0cfc0eba9f8bb
User: ewohlers
Project: calorimeterprojectdemo

null

**Comment by jmusacchio-gap** [comment]
Probably this is not happening anymore. Mark updated QA with a newer version that fixes this problem. Verify

**Comment by tdschenk** [comment]
I could not replicate anymore. Closing this issue.

**Comment by plbrownupnorth** [comment]
Erica and I saw this today (4/18) on staging server.

**Comment by tdschenk** [comment]
This was an issue with the JSON and not the backend. In the future it would be a good idea to include a link to what JSON bundle you tried to use, since there are now bundles for each lab. Only standard was tested when this issue was first closed.
