### ISSUE TITLE
500 error when trying to edit some Variables

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#528]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/project/components
User: ewohlers
Project: multiple_n2_test

Get a 500 error when trying to edit Diet, Exercise Level, Treatment. The others go to the edit screen when I press the blue pencil icon. I think the variables that give errors are all strings.

**Comment by jmusacchio-gap** [comment]
Fixed it adding a new alias for string setting. Right now text and string setting are handled in the same way. Waiting for a deploy to be pushed into QA

**Comment by plbrownupnorth** [comment]
We now get to edit window and can type in changes but changes are not saved. Hit save -reopen edit window. Changes not there.
