### ISSUE TITLE
Variable name overlap

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#529]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/project/components
User: ewohlers
Project: multiple_n2_test

I was able to create a Variable with the same name as an existing variable. PiLR should give an error if variable names are the same. 
Diet variable was created as part of an import. I created a second diet variable using the + button.

**Comment by tdschenk** [comment]
Variable creation does validation on the 'code' field, NOT the 'name' field. In this case the code field was different but the name field the same.

Do we want to also do validation on the name field?

**Comment by plbrownupnorth** [comment]
Yes. we need to check the Name Filed for duplicates as well

**Comment by plbrownupnorth** [comment]
Moved to an Assembla ticket.
