### ISSUE TITLE
multi-epoch participant variable setting view

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#530]
Server: qa.pilrhealth.com
Page: /project/nusi_demo_2/participant/show/57153ab8e4b0080a4984fa33
User: pbrown
Project: nusi_demo_2

Table not fitting in prescribed window--looks funny-can see through to content behind the table

**Comment by jmusacchio-gap** [comment]
Fixed it waiting for a deploy on QA
