### ISSUE TITLE
Epoch can't overlap error

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#532]
Server: qa.pilrhealth.com
Page: /project/nusi_demo_2/periodSchedule/update
User: ewohlers
Project: nusi_demo_2

See screen shot in comments

**Comment by ewohlers1** [comment]
![image](https://cloud.githubusercontent.com/assets/6774942/14618608/0cfd3c58-0579-11e6-9820-8a52c0fc1152.png)

**Comment by ewohlers1** [comment]
I was able to set epochs on overlapping days with different times when I select set by participant in the screen above and set the times under the participant.
