### ISSUE TITLE
Dashboards show in Job dropdown

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#534]
Server: qa.pilrhealth.com
Page: /project/multiple_n2_test/RProcEditor/participant
User: tschenk
Project: multiple_n2_test

From the first page of the R Processing Tool there is a dropdown to select an R job. Currently dashboards are also incorrectly being shown here.

Tyler is currently updating how jobs and dashboards are identified. Leave this issue open for now - will be addressed once those changes are in place.

**Comment by tdschenk** [comment]
This (along with related issues) was fixed with PR 329: https://github.com/MeiResearchLtd/s4r-general/pull/329
