### ISSUE TITLE
Observations on Users table

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#538]
Server: qa.pilrhealth.com
Page: /monitor/list
User: jmoon
Project: null

My login has access to just the table of users. That's good. 

Why is the table called "active users"? Are there other classes of user? Can we see them? If so, please change the name of the table to just "Users". If I'm not allowed to see other types of users, why is that? And if I can't see other user types why is there a "status" column in the table?

Please allow me to see many more than 10 rows of the table at a time.

**Comment by jmusacchio-gap** [comment]
The Status column shows the user account status like:

    expired("Expired", "The user account expired"),
    locked("Locked", "The user account is locked"),
    password_expired("Password Expired", "The user account password expired"),
    activation_expired("Activation Expired", "The user account activation expired"),
    active("Active", "The user account is active"),
    pending("Pending", "The user account is pending activation")

**Comment by jmusacchio-gap** [comment]
Added combo box to be able to see more than 10 rows. Renamed UI from "Active Users" to just "Users". Waiting for a Deploy.
