### ISSUE TITLE
Code changes in Name is editted

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#552]
Server: qa.pilrhealth.com
Page: /project/calorimeter_test_project/variable/editVariableDef
User: ewohlers
Project: calorimeter_test_project

null

**Comment by tdschenk** [comment]
When editing participant variables, the code field appears to change along with changes to the name. The code field also appears to be editable itself. However, the code field is actually never changed regardless of what is saved in the input boxes.

Solution would be to make the code field static and non-editable (grayed out).
