### ISSUE TITLE
Trigger set up page display

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#555]
Server: qa.pilrhealth.com
Page: /project/bariatric_ema_beta/trigger/index
User: pbrown
Project: bariatric_ema_beta

Actigraph Epoch event used to display just the initial portion of the java script function so that it fit nicely in the Event box. Now the entire thing is displayed and bleeds over into the conditions box. Looks messy!

**Comment by tdschenk** [comment]
Could this be a browser-specific issue? I am not able to replicate on my machine (tried on both qa and local).

**Comment by plbrownupnorth** [comment]
Mark fixed this for me.
