### ISSUE TITLE
Personal venues card error

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#561]
Server: cloud.pilrhealth.com
Page: /project/juan_test/participant/show/56f03cf3e4b03bb07548cd41
User: daperezalba
Project: common_places

It appears that the personal venues card is not storing data. I tried submitting it on my phone twice and but it does not appear in the Personal Venues datasets.

**Comment by plbrownupnorth** [comment]
User was working with older version of the app. Latest version of PiLR EMA has fixed this.
