### ISSUE TITLE
pilr_health_bulk_activate_device_feature_on_Staging

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#564]
Think this was reported and resolved on QA.  The bulk activate device feature looks like it works.  The screens in PiLR Health show the correct login id and set a password.  However, if you try to login in on a mobile device you get a "user not found" error message.

**Comment by tdschenk** [comment]
Seems like this has been fixed but has not been deployed to qa yet.

**Comment by ijafir** [comment]
fix was implemented

**Comment by plbrownupnorth** [comment]
Tested on cloud. Working now.
