### ISSUE TITLE
Bulk download of files, file name includes ID

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#570]
Server: cloud.pilrhealth.com
Page: /project/uw_football_team_study/data/index
User: daperezalba
Project: uw_football_team_study

We need to be able to bulk download files (e.g. audio and picture files) by project and by participant. File name also needs to include participant ID along with time stamp (e.g. ID_time stamp: 001_05-12-2016- 13:04:44) Preferably using something that is easy to identify to separate ID since our participant IDs have dashes (e.g. 00-00-0000).

**Comment by plbrownupnorth** [comment]
Moved to PiLR Health backlog
