### ISSUE TITLE
Uploading Data file - Participant not found error

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#573]
Server: qa.pilrhealth.com
Page: /project/testgfcustomization/participant/show/577161fae4b0deee23b2f31d
User: ewohlers
Project: testgfcustomization

When I try to upload a file for the example participant I get an error that the participant does not exist. When I go to the dashboard, the participant is there and the data file is in the file list.

**Comment by plbrownupnorth** [comment]
Moved to a ticket in Assembla
