### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#578]
Server: qa.pilrhealth.com
Page: /project/erictest2/project/design
User: eruud
Project: erictest2

The string "Setup and edit the design of the project (e.i. who uses what, when?)" should be "Setup and edit the design of the project (i.e. who uses what, when?)", changing e.i. to i.e.

**Comment by eruud** [comment]
The change in text is live, verified at /project/erictest2/project/design

**Comment by bikerjohn** [comment]
Tested and approved by Eric
