### ISSUE TITLE
Error 404 while creating quick plot

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#581]
Server: qa.pilrhealth.com
Page: /project/erictest2/quickPlotItem/save
User: eruud
Project: eric_test_project

Maybe because I didn't set a name/description?

**Comment by eruud** [comment]
Tested at project/erictest2/quickPlotItem/save, name is now a required field so the error is avoided

**Comment by bikerjohn** [comment]
Tested by Eric
