### ISSUE TITLE
Data field does not allow selection

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#582]
Server: qa.pilrhealth.com
Page: /project/erictest2/quickPlotItem/create
User: eruud
Project: eric_test_project

I was kicked here from the 404 page, it saved the selections for Datasets, Time Field, Color and Plot Type, but Data Field is grey and I cannot select a data field

**Comment by eruud** [comment]
This may have been fixed with #581
