### ISSUE TITLE
UI inconsistant

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#589]
Server: qa.pilrhealth.com
Page: /project/erictest2/evTagConfig/config
User: eruud
Project: erictest2

Pressing the "import content" button will highlight both the import content and export content buttons, pressing the "export content" button downloads the evtagger json file, but does not navigate me to a page

**Comment by tdschenk** [comment]
Fixed the first issue with button highlighting.
Second issue is intended behavior since only functionality for exporting all contents exists right now.
