### ISSUE TITLE
Cancel data upload error

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#592]
Server: qa.pilrhealth.com
Page: /project/cal_var_testing_2/dashboard/index
User: ewohlers
Project: cal_var_testing_2

When I press cancel on the data upload screen, it brings me to an error page. The top banner shows a different organization and project. The organization and project change each time I press cancel. Should go back to the page where the data upload button was pressed.

**Comment by tdschenk** [comment]
Cannot replicate this issue even on same project. Must have gotten fixed.
