### ISSUE TITLE
Vague error message when registering with an email already in use

### ISSUE THREAD

**Issue by gloery** [pilrhealth/pilrhealth-issues#6]
When a user tries to register with an email address that already has an account associated with it, they are successfully able to fill out the rest of the form and click register, but they are directed to a page where the only text is a bullet point saying "An error has occurred".

Note that it might not be the duplicate email address that's causing this, but I'm guessing it's a duplicate something.

**Comment by plbrownupnorth** [comment]
Tested with latest registration on qa. Get clear error message that email already in use.
