### ISSUE TITLE
Can remove lock/unlock permission from all users

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#610]
Server: localhost
Page: /project/calorimeter_2/project/admin
User: devuser-0
Project: calorimeter_2

Test:
Created project with single user
Removed lock/unlock permission from myself
Can no longer view lock/unlock page or grant that permission to anyone

Fix: Should require minimum of 1 user with this permission. Give error when trying to remove last user's permission. Does not need to be owner.

**Comment by tdschenk** [comment]
Need to also fix the case of deleting the last user with the lock permission

**Comment by jmusacchio-gap** [comment]
Done waiting for Mark to push it to QA
