### ISSUE TITLE
Participant Active Period showing Not scheduled

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#611]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0719-3/participant/show/579a257de4b0c77e0537fb9b
User: ewohlers
Project: calorimetertest0719-3

I schedule the period and see the green box on top of the screen saying it has been scheduled, but the schedule tab shows it is Not Scheduled. The settings and variables are available.

**Comment by ewohlers1** [comment]
![image](https://cloud.githubusercontent.com/assets/6774942/17218950/309b5b56-54af-11e6-8de9-8f698eb26880.png)

**Comment by ewohlers1** [comment]
I refreshed the screen. The green box went away, but the Participant Active period is shown as not scheduled. Existing participants (TestTRI) also have the active period showing as not scheduled, but I am able to run the processing jobs. 

I am available for a hangout to help troubleshoot.
