### ISSUE TITLE
Please correct errors below functionality

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#613]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/dataset/save
User: eruud
Project: blendertestproject

I have an error that says "please correct errors below" but no fields are highlighted. I think the error is because I tried to create a duplicate dataset

**Comment by bikerjohn** [comment]
Is it possible to provide a screen shot?

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17306832/b0bf711e-57f7-11e6-8113-1912d690a8f6.png)

**Comment by eruud** [comment]
In BlenderTestProject I created a dataset with all the fields as "test" except for the Code and Version (1)

**Comment by jmusacchio-gap** [comment]
The fix will be available on next push

**Comment by eruud** [comment]
It detects missing fields but now it doesn't save every field so more than the highlighted field will be required to submit this dataset without an error

![image](https://cloud.githubusercontent.com/assets/19293109/17410176/35a762fa-5a38-11e6-8508-4ba8d496b0ae.png)

**Comment by jmusacchio-gap** [comment]
Added the code to avoid clearing already filled fields if the validation fails.

**Comment by eruud** [comment]
Tested the saving of fields with errors, works as expected and error correction process is intuitive now.
