### ISSUE TITLE
Behavior when file exists

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#615]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/upload/step1
User: eruud
Project: blendertestproject

If I try to upload a file that already exists, I get sent back to the upload page with no error

**Comment by jmusacchio-gap** [comment]
The fix will be available on next push

**Comment by eruud** [comment]
I now get an error if I try to reupload a file with an identical name to one that exists so this is fixed.

![image](https://cloud.githubusercontent.com/assets/19293109/17410353/e608d3a4-5a38-11e6-8383-8c994cdfed19.png)

**Comment by bikerjohn** [comment]
Tested and approved by Eric
