### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#616]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/data/deleteData
User: eruud
Project: blendertestproject

I think "Showing all Dataset." should be "Showing all Datasets." at the bottom of the Dataset History page

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17307310/0bbfae88-57fa-11e6-831f-0dd896e3cffa.png)

**Comment by jmusacchio-gap** [comment]
The fix will be available on next push

**Comment by eruud** [comment]
The text is updated at /project/blendertestproject/data/deleteData so this is fixed

**Comment by bikerjohn** [comment]
Tested and approved by Eric
