### ISSUE TITLE
UI - "Delete Data" button

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#617]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/dashboard/index
User: eruud
Project: blendertestproject

There is an extra space to the left of the text

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17307379/68350f3c-57fa-11e6-8094-45c3b6311abb.png)

**Comment by eruud** [comment]
Also in the Actions menu at https://qa.pilrhealth.com/project/blendertestproject/participant/show/
![image](https://cloud.githubusercontent.com/assets/19293109/17338147/af7efaea-58ab-11e6-8edf-fe0282741aac.png)
All the labels have a space before except Bulk edit

**Comment by jmusacchio-gap** [comment]
The fix will be available on next push
