### ISSUE TITLE
UI improvement for popup box

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#619]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/project/components
User: eruud
Project: blendertestproject

It would be nice if when I clicked the "code" icon, clicking the box that comes up did not cause it to disappear, so you can copy the code. If you clicked outside of the box, it would still disappear.

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17333514/5b8aa3d4-5898-11e6-9d0c-68045931e7e5.png)

**Comment by jmusacchio-gap** [comment]
The fix will be available on next push

**Comment by eruud** [comment]
I can now select the text in the box, so this is working

![image](https://cloud.githubusercontent.com/assets/19293109/17410493/89433334-5a39-11e6-8ef2-c2882ce96360.png)

**Comment by bikerjohn** [comment]
tested and approved by Eric
