### ISSUE TITLE
Dataset description

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#621]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/project/components
User: eruud
Project: blendertestproject

Change it's to its in "There are 8 datasets enabled for this project. Each dataset schema defines a format of the data records that can be stored in the database. Click on a dataset schema version below to view it's defined data fields and structure."

http://www.bristol.ac.uk/arts/exercises/grammar/grammar_tutorial/page_13.htm

**Comment by eruud** [comment]
Text is updated at /project/blendertestproject/project/components so this is fixed

**Comment by bikerjohn** [comment]
Tested and Approved by Eric
