### ISSUE TITLE
Wrapping of Schema text

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#623]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/schema/show/57a0b6aae4b001a9c88275df
User: eruud
Project: blendertestproject

The Schema Version Number text wraps to the next line while the data is on the first line

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17338047/3d7cf3d4-58ab-11e6-8ce7-e3890c251725.png)

**Comment by plbrownupnorth** [comment]
Erica and Phyllis reviewed. Just change text from Schema Version Number to Schema Version.

**Comment by eruud** [comment]
The text is changed at /project/blendertestproject/schema/show/57a0b6aae4b001a9c88275df so this is fixed

**Comment by bikerjohn** [comment]
Tested and approved by Eric
