### ISSUE TITLE
Dataset or Participant not found error

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#625]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0719-3/data/index/578e2c9ce4b01851b05fb35e
User: eruud
Project: calorimetertest0719-3

Participant epochtest2 on
CalorimeterTest0719-3
I cannot look at the data though on import it says successfully parsed 
Using the "View Data" tool from the imported file details
The scheduling may not be setup correctly but no errors are shown

**Comment by eruud** [comment]
This is using the "View Data" button for the first datafile stored with epochtest2

![image](https://cloud.githubusercontent.com/assets/19293109/17405455/1facb404-5a25-11e6-84a6-f05dde92335f.png)

**Comment by jmusacchio-gap** [comment]
Was passing incorrectly the participant code to the controller when clicking on View Data link.

**Comment by eruud** [comment]
Now fixed/tested for the reported participant and new participants. 

Can be closed
