### ISSUE TITLE
500 Error accessing default template

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#626]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0719-3/template/show/578e2ca5e4b01851b05fb3e0
User: eruud
Project: calorimetertest0719-3

I get a 500 error when clicking the "Default Template" link. I just added 2 Epochs to the period

**Comment by eruud** [comment]
Also at https://qa.pilrhealth.com/project/erictest2/template/show/577d7b82e4b03069189bfb30

**Comment by jmusacchio-gap** [comment]
Was allowing to add period schedule objects without a period associated to it. Switched nullable constraint.

**Comment by eruud** [comment]
The issue was caused when a schedule was "added" through UI with no schedule selected as discussed on Slack. The changes now prevent this from happening by requiring a schedule.

Can be closed.
