### ISSUE TITLE
Template detail description

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#634]
Server: qa.pilrhealth.com
Page: /project/erictest2/project/components
User: eruud
Project: erictest2

Change it's to its in text

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17382715/e3c5ae38-5997-11e6-9675-98922fee21d6.png)

**Comment by eruud** [comment]
Click the "Templates" button from the Instruments section of the Settings page to see the pop-up. The error is still there.

**Comment by eruud** [comment]
Language has been corrected
