### ISSUE TITLE
Epoch ordering

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#635]
Server: qa.pilrhealth.com
Page: /project/erictest2/template/show/57a26075e4b083079321cefb
User: eruud
Project: erictest2

Epochs are not listed in chronological order here, but they are from the participant schedule (https://qa.pilrhealth.com/project/erictest2/participant/show/57a26158e4b083079321cf0d)

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17382875/c3f54072-5998-11e6-8eb0-487a423cc3ba.png)

**Comment by jmusacchio-gap** [comment]
Added a new method to sort the EpochSchedule by start day.

**Comment by eruud** [comment]
Looks good, they are now organized by date

![image](https://cloud.githubusercontent.com/assets/19293109/17419334/88a76034-5a62-11e6-8d9a-8e161fe84a46.png)
