### ISSUE TITLE
Human CalRQ Participant Variable CSV Export

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#636]
Server: qa.pilrhealth.com
Page: /project/erictest2/RProcEditor/details/57a268a7e4b083079321dab9
User: eruud
Project: erictest2

The CSV export of Participant Variables after the R Human Summary job is complete only includes the data from the first Epoch in the list (which is not necessarily the first Epoch consecutively). The CSV may be easier to read if it matched the PiLR display of variables, though as long as it has all the information any format should work.

**Comment by jmusacchio-gap** [comment]
Fixed the issue, was not exporting all the data correctly.

**Comment by eruud** [comment]
New export seems to be missing rest_durations

![image](https://cloud.githubusercontent.com/assets/19293109/17484182/6a2af492-5d4e-11e6-8af5-82a6003cca25.png)

**Comment by jmusacchio-gap** [comment]
Can you verify whether the variable is displayed on the UI (before exporting it) and attach an screenshot. Can you add me to the project?

**Comment by eruud** [comment]
The project is EricTest2. I think the issue was that the human job export I compared to was GF Custom 1.1 which has a variable for rest_durations, while the latest human job doesn't. So it is behaving as expected

**Comment by jmusacchio-gap** [comment]
Can you close it?
