### ISSUE TITLE
500 error accessing quickplot options

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#638]
Server: qa.pilrhealth.com
Page: /project/erictest2/quickPlotItem/index
User: eruud
Project: erictest2

Changing quickplot options, now have a 500 error. Will try to find steps to reproduce outside of this project

**Comment by eruud** [comment]
If you put in a name and time field, then press submit, it will not trigger a required field error but you will get a 500 error

**Comment by jmusacchio-gap** [comment]
Missing validation of QuickPlotField when saving the object (create and update). Was allowing to store a QuickPlotField without a dataset associated.

**Comment by eruud** [comment]
If I select a dataset the Data Field becomes available. If I select a dataset then press back, then go forward, the Data Field dropdown is unavailable. This is probably more related to #582 though

**Comment by jmusacchio-gap** [comment]
Added the code to perform ajax request on page load whether data set is not null and data field is null so we avoid this issue.

**Comment by eruud** [comment]
The datafield is now selectable after a page change, this can be closed.
