### ISSUE TITLE
Permissions summary in administration

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#639]
Server: qa.pilrhealth.com
Page: /project/erictest2/project/admin
User: eruud
Project: erictest2

Why does lock show up twice in my list of permissions?

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17412596/2fa7478e-5a43-11e6-917a-cbc783b971c7.png)

**Comment by eruud** [comment]
No longer see duplicate of lock permission in my projects
