### ISSUE TITLE
User information in administration

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#640]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0719-3/project/admin
User: eruud
Project: calorimetertest0719-3

Is it possible to include more information about a user somewhere in case they have multiple accounts under their name?

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17413030/4544909a-5a45-11e6-98f5-910a762bfc44.png)

**Comment by eruud** [comment]
The User link 404 bug is reported in https://github.com/pilrhealth/pilrhealth-issues/issues/693

**Comment by eruud** [comment]
There is now a detail button which displays the email associated with the user, which avoids confusion when multiple accounts are used for a single name.
