### ISSUE TITLE
Duplicate files not rejected

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#641]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0804/data/index
User: eruud
Project: calorimetertest0804

Using the file handler https://github.com/pilrhealth/definition-files/blob/master/standard/CalRQ/calrq-data-file-handler.json, duplicate files are uploaded with a (number), we would like to reject duplicate files as in #615

**Comment by jmusacchio-gap** [comment]
Refactored the method to reject duplicates

**Comment by eruud** [comment]
Not sure if this is cause by recent update or untested error with #615, but if I upload an identical file on different days I don't seem to get an error, it should be rejected. PiLR adds a datestamp to the filename based on upload date, so if the post-upload filename is used for this check that could be an issue.

![image](https://cloud.githubusercontent.com/assets/19293109/17483019/fa7c0928-5d49-11e6-93a5-321c02af544d.png)

**Comment by jmusacchio-gap** [comment]
Removed timestamp from uploaded file name so now it going to reject duplicates from different dates also.

**Comment by eruud** [comment]
Okay, without the timestamp the filenames will be duplicates and we still have the upload date stored in the file details, so it looks good now
