### ISSUE TITLE
Participant deletion

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#642]
Server: qa.pilrhealth.com
Page: /participant/save
User: eruud
Project: calorimetertest0804

If I delete a participant then create a participant with the same name, I get an error in creation that says the name field must be unique. I can also access the deleted participant with the old URLs.

**Comment by eruud** [comment]
I can also still see them in bulk edit

**Comment by jmusacchio-gap** [comment]
Missing validations on show particpant page to avoid displaying a deleted participant. Missing filter on bulk edit query to avoid loading deleted participants.

**Comment by eruud** [comment]
Deleted participants now no longer accessible from URL, do not show up in bulk edit

Can be closed

**Comment by jmusacchio-gap** [comment]
I cannot reproduce it for the moment, so if you find a way let me know.

**Comment by eruud** [comment]
Closed, will reopen if I see it again.
