### ISSUE TITLE
Epochs do not match period in R Processing Tool

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#643]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0804_2/RProcEditor/participantJobConfig
User: eruud
Project: calorimetertest0804_2

When I select the period MultiEpochTest, which has multiple epochs, the Epoch selection only has Epochs listed for the default period

**Comment by eruud** [comment]
I'm not sure if this is how multiple Epochs are expected to be setup, the project is caloriemtertest0804_2

![image](https://cloud.githubusercontent.com/assets/19293109/17419197/f51adb7a-5a61-11e6-8249-f660aaef5b3e.png)
![image](https://cloud.githubusercontent.com/assets/19293109/17419207/03b508fe-5a62-11e6-84c4-2f4d9864a7d9.png)

**Comment by jmusacchio-gap** [comment]
Was missing a temlate that fetches epochs when picking period. Added some extra validations also.

**Comment by eruud** [comment]
I can now select by Epoch as expected so this UI issue is fixed, noted some possible issues with epochs in #646
