### ISSUE TITLE
Missing text on group categories page

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#644]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0804/project/groupCategories
User: eruud
Project: calorimetertest0804

The second bullet point reads "of 8 participants are in at least one group category.", is there supposed to be a number before "of"?

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/17419907/489b7504-5a65-11e6-904b-bc9c04feb478.png)

**Comment by eruud** [comment]
Now displays number of participants in category as expected.
