### ISSUE TITLE
Import project bundle error

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#673]
Server: qa.pilrhealth.com
Page: /project/testnusi_import/project/components
User: ewohlers
Project: testnusi_import

I get the following error when trying to import a bundle created using the export bundle from an existing project.
 Failed to add the project components. Unfriendly error message was >>>> Cannot get property 'activeInstruments' on null object

**Comment by jmusacchio-gap** [comment]
The issue here is that there is already a template with name "Default Template" but it has a different code so it is failing to create a new template due to unique template name constraint by project. Need instructions how to fix this (business guidelines)
