### ISSUE TITLE
Language list

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#681]
Server: cloud.pilrhealth.com
Page: /project/belt__road/emaOts/language
User: jmoon
Project: belt__road

The list of languages available in the EMA builder still has only one entry for Chinese. I'm not sure when the full ISO list will propagate to beta, but we should ensure that all choices are selectable. 

Also, we still need to change the explanatory text. First the box label should say "Selected Languages". Below the box it should read, "Click in the box to show the list of available languages and select languages for your project. English is default". Don't mention of ISO codes.

**Comment by jmusacchio-gap** [comment]
Already changed the texts on languages screen, a new deploy will impact the change.
