### ISSUE TITLE
Auto-enroll URL shouldn't be restricted from copy

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#687]
Server: cloud.pilrhealth.com
Page: /project/belt__road/group/editGroup/57c032aae4b0180a0a2018cc
User: jmoon
Project: belt__road

The URL for the auto enroll function is blocked from being copied. I expect it's completely blocked to prevent accidental editing. But the way we've done it means that for the URL to be shared our Users have to retype it by hand. That could lead to errors. Is there some way to allow it to be copied but not allow any accidental changes to be saved?

**Comment by bikerjohn** [comment]
I am closing this issue, as it is incorrect in reporting the problem as the URL cannot be copied.  I will open a different issue with the correct problem being identified.
