### ISSUE TITLE
User sort function

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#693]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0719-3/project/admin
User: eruud
Project: calorimetertest0719-3

Pressing the "User" column name results in a 404 page. I'm not sure if it's supposed to sort the users differently or if it shouldn't be a link at all.

**Comment by eruud** [comment]
By default, users are sorted by addition date(?). Clicking the User column sorts alphabetically by first name, and clicking it again reverses that. The 404 error when clicking "User" has been fixed.
