### ISSUE TITLE
Send screenshot to support function

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#694]
Server: qa.pilrhealth.com
Page: /RProcEditor/history
User: eruud
Project: blendertestproject

Change the "an" to "a" in the "Click on the camera to send an screenshot..." string

**Comment by eruud** [comment]
Also, where do screenshots get sent to? Does it just include the PiLR error, entire webpage, or entire desktop?

**Comment by jmusacchio-gap** [comment]
Screenshots are being sent to support@pilrhealth.com and is an screenshot of the entire PiLR webpage that the user is watching at that time.

**Comment by eruud** [comment]
Language has been corrected
