### ISSUE TITLE
TSV file support

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#705]
Server: qa.pilrhealth.com
Page: /project/blendertestproject/participant/show/579f86e0e4b050939ac42984
User: eruud
Project: blendertestproject

TSV file are CSV files but with tab (\t) as a deliminator. It would be nice if they could be previewed like CSV files are in PiLR.
In the User Data tab they are previewed as an image, which doesn't work. Maybe the preview should be removed for files CalRQ does not recognize?

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/18283238/e5f59874-7429-11e6-87ef-efbc1c865410.png)

**Comment by jmusacchio-gap** [comment]
Will be ready for test on next deploy

**Comment by eruud** [comment]
The previews work as expected, but the quickinfo Content type information doesn't reflect the file. Is this set in the backend or is it a filetype definition setting?

CSV File:
![image](https://cloud.githubusercontent.com/assets/19293109/19247422/e3407fd6-8ef0-11e6-9de3-b69b838ae166.png)

TSV File:
![image](https://cloud.githubusercontent.com/assets/19293109/19247431/ea427820-8ef0-11e6-8582-230e237387cb.png)

**Comment by eruud** [comment]
Content type now shows up as TSV
