### ISSUE TITLE
Not authorized to view this page on login

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#706]
Server: qa.pilrhealth.com
Page: /
User: eruud
Project: null

From https://qa.pilrhealth.com/login/auth, if I double-click "login", nothing happens. If I click "login" again after that, I get sent to https://qa.pilrhealth.com/grails-errorhandler, which says "Sorry, you're not authorized to view this page.", instead of logging me in.

**Comment by jmusacchio-gap** [comment]
Fixed it avoiding twice form submition

**Comment by jmusacchio-gap** [comment]
Related to this issue grails-plugins/grails-spring-security-core#85 upgreaded from spring-security-core:2.0-RC2 to spring-security-core:2.0.0 release version.

**Comment by eruud** [comment]
Double-clicking now has the same behavior as single-clicking, and logging in when you are already logged in just sends you to the homepage instead of an error so this is resolved
