### ISSUE TITLE
500 Error returned when running R Processing Job

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#709]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0804_2/RProcEditor/details/57d0d675e4b0e28b037cf8f9
User: eruud
Project: calorimetertest0804_2

When running an R processing job a 500 error is returned via text in the History section:

`{ "date" : { "$date" : "2016-09-08T03:09:43.211Z"} , "status" : "ERROR" , "message" : "Job Failed. Response code was 500: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>500 Internal Server Error</title>\n</head><body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error or\nmisconfiguration and was unable to complete\nyour request.</p>\n<p>Please contact the server administrator at \n webmaster@localhost to inform them of the time this error occurred,\n and the actions you performed just before this error.</p>\n<p>More information about this error may be available\nin the server error log.</p>\n<hr>\n<address>Apache/2.4.7 (Ubuntu) Server at 172.31.48.20 Port 80</address>\n</body></html>\n"}`

**Comment by tdschenk** [comment]
This is a result of our recent OpenCPU issues. Can be closed once that is fixed

**Comment by eruud** [comment]
R processing jobs now run as expected
