### ISSUE TITLE
Limit on custom PiLR EMA app name characters

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#712]
Server: cloud.pilrhealth.com
Page: /project/buckeye_teen_healthtest/emaOts/application
User: pbrown
Project: buckeye_teen_healthtest

Get 500 error if type in long name; OK with shorter name; we should simply limit number of characters that can be entered by User to number that is acceptable

**Comment by tdschenk** [comment]
On qa, character entry is limited, so this should be fixed with next release to cloud.
