### ISSUE TITLE
Owners can remove themselves from a project

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#716]
Server: qa.pilrhealth.com
Page: /project/calorimetertest516/dashboard/index
User: eruud
Project: calorimetertest516

You need to give someone else lock permission to leave a project, but the owner can leave the project and ownership is not transfered. There is not a mechanism to change owner in the UI that I can see.

**Comment by eruud** [comment]
When the owner tries to remove themselves from the project they now receive the error message "The owner of the project cannot be removed from Project Team." and are not removed from the project, preventing this error
