### ISSUE TITLE
Invalid Date message when selecting study dates

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#734]
Server: qa.pilrhealth.com
Page: /project/assemblatests/upload/step2
User: eruud
Project: assemblatests

When uploading a CalRQ CSV file I can select by epochs but when I try to select by dates I get Invalid date errors

Created test project AssemblaTests
Imported bundle https://github.com/pilrhealth/definition-files/blob/master/standard/CalRQ/setup-bundle-1.json
Scheduled participant active period in template
Set Epochs

**Comment by eruud** [comment]
![image](https://cloud.githubusercontent.com/assets/19293109/20222654/c1fb31da-a7fb-11e6-869b-b4edc4d01bfd.png)

**Comment by eruud** [comment]
https://github.com/pilrhealth/pilrhealth-issues/issues/736
