### ISSUE TITLE
"Invalid Date" error with Date Range selector

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#736]
Server: qa.pilrhealth.com
Page: /project/testtyler1/upload/step2
User: tschenk
Project: testtyler1

When uploading a file that has an associated job, you are presented with an option to either use the scheduled period or a date range. If you select the date range option, there is a bug with the date selector and it is just showing "Invalid Date".

Note: The CalRQ CSV File handler is the only file handler that has a job associated with it. You can import the CalRQ Bundle to use it.

**Comment by tdschenk** [comment]
![invalid date error](https://cloud.githubusercontent.com/assets/5633138/20229542/aff7b78a-a81c-11e6-8047-79761cf57357.png)

**Comment by jmusacchio-gap** [comment]
Fixed it, will be ready for test on next QA deploy
