### ISSUE TITLE
Hide_cards vs. hide_questions

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#759]
Server: cloud.pilrhealth.com
Page: /project/cchmc_demo/emaOtsConfig/editSurveyRules
User: wolf9d
Project: cchmc_demo

Hi guys,

I noticed that I the example code for branching has the action 'hide_cards.'  I used 'hide_questions' after I read down the page and that has worked.  

Is 'hide_cards' for a different action?

Thanks!

Chris

**Comment by plbrownupnorth** [comment]
Ticket written on this one in Assembla.
