### ISSUE TITLE
Logo function broken

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#762]
Server: cloud.pilrhealth.com
Page: /project/brown_caas/emaOts/saveApplication
User: jmoon
Project: brown_caas

When I upload a new logo file it seems to reach PiLR and is displayed after pushing 'Save'. Push 'Save' again and it goes away. No combination of 'Saves', uploads, etc results in the logo reaching the app.

**Comment by plbrownupnorth** [comment]
Ticket is written on this one in Assembla
