### ISSUE TITLE
POST only showing existing data, but not uploading new data

### ISSUE THREAD

**Issue by krishna-nag** [pilrhealth/pilrhealth-issues#768]
POST . /api/v{version}/{project code}/instrument/{instrument code}/participant/{participant code}/dataset/{dataset code}/{schema version}/data is supposed to add new data to the dataset, where data is the body. But, the post request receives a response, which is the existing data in the dataset, but doesn't upload anything.

I am using Postmaster app for testing the POST request. The authorisation is successful, because it is returning with the data in the dataset, but is not uploading anything to the dataset.

Can you please help me. Is there a setting that enables writing into the dataset? It is said that ifthe validation of the data fails, it will be stored in a temporary bin file. Where can I find this>

**Comment by plbrownupnorth** [comment]
Mark worked with Krishna on this.
