### ISSUE TITLE
When adding new epoch, existing participants don't update automatically

### ISSUE THREAD

**Issue by gloery** [pilrhealth/pilrhealth-issues#92]
Currently, if we create a participant, then add an epoch to the period the participant belongs to (and set the epoch span), if we go back to /participant/show, the new epoch will appear as "not set" instead of automatically picking up where the previous epoch ends. Is this expected behavior, or should the new epoch automatically be scheduled for that participant when it is added?

**Comment by jamespshields** [comment]
This is by design. Changes can be propagated by re-scheduling the participant.
